"""initial schema

Revision ID: 4dd4e0c0209f
Revises: 
Create Date: 2026-09-08 08:39:44.173854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4dd4e0c0209f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_scenario_user_name')
    )
    op.create_index(op.f('ix_scenarios_user_id'), 'scenarios', ['user_id'], unique=False)
    op.create_table('dependents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('current_age', sa.Integer(), nullable=False),
    sa.Column('school_fee_today', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('school_fee_hike', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('school_fee_hike_frequency', sa.Integer(), nullable=False),
    sa.Column('school_end_age', sa.Integer(), nullable=False),
    sa.Column('graduation_cost_today', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('graduation_inflation', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('graduation_start_age', sa.Integer(), nullable=False),
    sa.Column('graduation_duration', sa.Integer(), nullable=False),
    sa.Column('inflate_graduation_instalments', sa.Boolean(), nullable=False),
    sa.Column('marriage_cost_today', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('marriage_inflation', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('marriage_age', sa.Integer(), nullable=True),
    sa.Column('fund_school_from_corpus_pre_retirement', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependents_scenario_id'), 'dependents', ['scenario_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('amount_today', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('at_age', sa.Integer(), nullable=False),
    sa.Column('inflation', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('recurrence', sa.String(length=20), nullable=False),
    sa.Column('recurrence_years', sa.Integer(), nullable=True),
    sa.Column('duration_years', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_scenario_id'), 'goals', ['scenario_id'], unique=False)
    op.create_table('income_streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('monthly_amount_today', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('start_age', sa.Integer(), nullable=False),
    sa.Column('end_age', sa.Integer(), nullable=True),
    sa.Column('annual_escalation', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_streams_scenario_id'), 'income_streams', ['scenario_id'], unique=False)
    op.create_table('scenario_inputs',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('current_age', sa.Integer(), nullable=False),
    sa.Column('retirement_age', sa.Integer(), nullable=False),
    sa.Column('life_expectancy', sa.Integer(), nullable=False),
    sa.Column('plan_start_year', sa.Integer(), nullable=False),
    sa.Column('current_corpus', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('monthly_contribution', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('contribution_stepup', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('contributions_stop_age', sa.Integer(), nullable=True),
    sa.Column('pre_retirement_return', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('post_retirement_return', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('annual_expense_today', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('expense_inflation', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('charge_household_expense_pre_retirement', sa.Boolean(), nullable=False),
    sa.Column('medical_expense_today', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('medical_inflation', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('post_retirement_expense_factor', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('engine_mode', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_inputs')
    op.drop_index(op.f('ix_income_streams_scenario_id'), table_name='income_streams')
    op.drop_table('income_streams')
    op.drop_index(op.f('ix_goals_scenario_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_dependents_scenario_id'), table_name='dependents')
    op.drop_table('dependents')
    op.drop_index(op.f('ix_scenarios_user_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
